-- Feel free to add more. The more the better.

Insert into ingredients (id, name) VALUE (1, "Milk");
Insert into ingredients (id, name) VALUE (2, "Flour");
Insert into ingredients (id, name) VALUE (3, "Salt");
Insert into ingredients (id, name) VALUE (4, "Pepper");
Insert into ingredients (id, name) VALUE (5, "Garlic");
Insert into ingredients (id, name) VALUE (6, "Butter");
Insert into ingredients (id, name) VALUE (7, "Rice");
Insert into ingredients (id, name) VALUE (8, "Water");
Insert into ingredients (id, name) VALUE (9, "Olive Oil");
Insert into ingredients (id, name) VALUE (10, "Chicken");
Insert into ingredients (id, name) VALUE (11, "Ground Beef");
Insert into ingredients (id, name) VALUE (12, "Bread");
Insert into ingredients (id, name) VALUE (13, "Yeast");
Insert into ingredients (id, name) VALUE (14, "Sausage");
Insert into ingredients (id, name) VALUE (15, "Honey");
Insert into ingredients (id, name) VALUE (16, "Ginger");
Insert into ingredients (id, name) VALUE (17, "Sugar");
Insert into ingredients (id, name) VALUE (18, "Diced Onions");
Insert into ingredients (id, name) VALUE (19, "Spinach");
Insert into ingredients (id, name) VALUE (20, "Parsley");
Insert into ingredients (id, name) VALUE (141, "Cream");
Insert into ingredients (id, name) VALUE (77, "Sauce");
Insert into ingredients (id, name) VALUE (41, "Cheese");
Insert into ingredients (id, name) VALUE (414, "Pepperoni");
Insert into ingredients (id, name) VALUE (21, "Baking Powder");
Insert into ingredients (id, name) VALUE (22, "Raisins");
Insert into ingredients (id, name) VALUE (23, "Avocado");
Insert into ingredients (id, name) VALUE (24, "Chili Powder");
Insert into ingredients (id, name) VALUE (25, "Green Bell Pepper");
Insert into ingredients (id, name) VALUE (26, "Carrots");
Insert into ingredients (id, name) VALUE (27, "Beets");
Insert into ingredients (id, name) VALUE (28, "Sour Cream");
Insert into ingredients (id, name) VALUE (29, "Potatoes");
Insert into ingredients (id, name) VALUE (30, "Celery");
Insert into ingredients (id, name) VALUE (31, "Lemon Juice");
Insert into ingredients (id, name) VALUE (32, "Mushrooms");